@startuml

Fragment <|-- BillMainFragment
class BillMainFragment{
    +{static}CategorySelectorState
    +{static}CategorySelectorChangeEvent
    #ViewPager;
    #DataSelectView;

}
ViewPager <--> DataSelectView
CategorySelectorState --> BillModule

BillMainFragment --> MonthPagerAdapter
BillMainFragment --> YearPagerAdapter
BillMainFragment --> CustomPagerAdapter

CalendarModel <|.. MonthPagerAdapter
CalendarModel <|.. YearPagerAdapter
CalendarModel <|.. CustomPagerAdapter

MonthPagerAdapter --|> FragmentStatePagerAdapter
YearPagerAdapter --|> FragmentStatePagerAdapter
CustomPagerAdapter --|> FragmentStatePagerAdapter

@enduml